model:
  pretrained: "HuggingFaceH4/zephyr-7b-beta" # pretrained=model_name,trust_remote_code=boolean,revision=revision_to_use,model_parallel=True ...
  revision: "main" # revision to use
  dtype: "4bit"  # Specifying the model to be loaded in 4 bit uses BitsAndBytesConfig. The other option is to use "8bit" quantization.
  compile: true
  delta_weights: false # set to True of your model should be merged with a base model, also need to provide the base model name
  adapter_weights: false # set to True of your model has been trained with peft, also need to provide the base model name
  base_model: null # path to the base_model - needs to be specified only if delta_weights or adapter_weights is set to True
  batch_size: 1 # batch size to use
generation:
  multichoice_continuations_start_space: null # If true/false, will force multiple choice continuations to start/not start with a space. If none, will do nothing
