model:
  base_params:
    model_args: "pretrained=NousResearch/DeepHermes-3-Llama-3-8B-Preview,revision=main,dtype=bfloat16,max_model_length=21000"
  generation:
    temperature: 0.3
    repetition_penalty: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    seed: 42
    top_k: -1
    min_p: 0.0
    top_p: 0.9
    max_new_tokens: 12000
