name: Slow end to end tests

on:
  push:
    branches:
      - main
      - v*-release
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run tests
    runs-on: 'aws-g4dn-2xlarge-use1-public-80'
    steps:
      - name: Install Git LFS
        run: |
          if ! command -v git-lfs &> /dev/null; then
            echo "Installing Git LFS..."
            sudo apt-get update && sudo apt-get install -y git-lfs
            git lfs install
          else
            echo "Git LFS already installed."
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: cache/models
          key: hf-models-${{ runner.os }}-${{ github.ref }}
          restore-keys: hf-models-${{ runner.os }}-

      - name: Cache Hugging Face datasets
        uses: actions/cache@v4
        with:
          path: cache/datasets
          key: hf-datasets-${{ runner.os }}-${{ github.ref }}
          restore-keys: hf-datasets-${{ runner.os }}-

      - name: Cache uv virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: uv-env-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: uv-env-${{ runner.os }}-

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --extra dev

      - name: Ensure cache directories exist
        run: mkdir -p cache/models cache/datasets

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TEST_TOKEN }}  # Ensure secret is explicitly passed
          HF_HOME: "cache/models"
          HF_DATASETS_CACHE: "cache/datasets"
        run: uv run pytest --disable-pytest-warnings --runslow tests/slow_tests
